// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models.DataBase;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251101000000_add_payment_transactions")]
    partial class add_payment_transactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.DataBase.User", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("varchar(50)");

                b.Property<int>("Credits")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0)
                    .HasComment("可用积分");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("varchar(100)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasComment("密码hash");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("varchar(20)");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            modelBuilder.Entity("Server.Models.DataBase.PaymentTransaction", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("char(36)");

                b.Property<decimal>("Amount")
                    .HasColumnType("decimal(10,2)");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("varchar(8)")
                    .HasDefaultValue("USD");

                b.Property<int>("Credits")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<string>("GatewayTransactionId")
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)");

                b.Property<string>("HostedPaymentToken")
                    .HasMaxLength(512)
                    .HasColumnType("varchar(512)");

                b.Property<string>("InvoiceNumber")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<string>("ItemsJson")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("varchar(32)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)");

                b.HasKey("Id");

                b.HasIndex("InvoiceNumber")
                    .IsUnique();

                b.ToTable("PaymentTransactions");
            });
#pragma warning restore 612, 618
        }
    }
}